name: test_dart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  hive: ^1.4.1+1
  sqlite3: ^0.1.8


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
  

