name: test_dart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  hive: ^1.4.1+1
  http: ^0.13.3
  path: ^1.7.0
  sqlite3: ^0.1.8

dev_dependencies:
  build_runner: ^1.8.0
  hive_generator: ^0.7.0+2
  pedantic: ^1.9.0
  test: ^1.14.4
