name: test_dart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  hive: ^2.0.4
  http: ^0.13.4
  path: ^1.8.0
  sembast: ^3.1.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
